from __future__ import annotations

import hashlib
import json
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Sequence, Tuple

ROLES = ("berry", "ingredient", "skill")
ANCHORS = (50, 60, 70, 80)
ANCHOR_WEIGHTS = {50: 0.15, 60: 0.30, 70: 0.20, 80: 0.35}
# Fixed 90th-percentile ideal-final-evolution baselines generated by the pinned
# Neroli engine (`mode=score-references`). They are independent of the box.
ABSOLUTE_REFERENCES = {
    50: {"berry": 2522.0, "ingredient": 2326.0, "skill": 5105.0},
    60: {"berry": 3300.0, "ingredient": 3678.0, "skill": 5224.0},
    70: {"berry": 4306.0, "ingredient": 4818.0, "skill": 5343.0},
    80: {"berry": 6884.0, "ingredient": 6065.0, "skill": 5970.0},
}
ZERO_VALUE_SUBSKILLS = {
    "Research EXP Bonus", "Sleep EXP Bonus", "Dream Shard Bonus"
}

# Base energy added by one ingredient when it is put into a dish. These values
# are also used by the pinned Neroli engine's RP ingredient component.
INGREDIENT_BASE_ENERGY = {
    "Apple": 90, "Milk": 98, "Soybean": 100, "Honey": 101,
    "Sausage": 103, "Ginger": 109, "Tomato": 110, "Egg": 115,
    "Oil": 121, "Potato": 124, "Herb": 130, "Corn": 140,
    "Cacao": 151, "Coffee": 153, "Avocado": 162, "Mushroom": 167,
    "Leek": 185, "Pumpkin": 250, "Tail": 342, "Slowpoke Tail": 342,
}


def now() -> str:
    return datetime.now(timezone.utc).isoformat()


def canonical_uid(item: Mapping[str, Any]) -> str:
    core = {
        "species": item["species"],
        "nature": item["nature"],
        "ingredients": item["ingredients"],
        "subskills": item["subskills"],
        "main_skill": item["main_skill"],
        "skill_level": item["skill_level"],
        "display_name": item.get("display_name") or "",
    }
    raw = json.dumps(core, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(raw.encode()).hexdigest()[:20]


def connect(path: Path) -> sqlite3.Connection:
    path.parent.mkdir(parents=True, exist_ok=True)
    db = sqlite3.connect(str(path))
    db.row_factory = sqlite3.Row
    db.executescript(Path(__file__).with_name("schema.sql").read_text())
    columns = {row["name"] for row in db.execute("PRAGMA table_info(individual)")}
    if "pokemon_type" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN pokemon_type TEXT")
    if "island_scores_json" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN island_scores_json TEXT NOT NULL DEFAULT '{}'")
    if "berry" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN berry TEXT")
    if "energy_scores_json" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN energy_scores_json TEXT NOT NULL DEFAULT '{}'")
    if "review_confirmed" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN review_confirmed INTEGER NOT NULL DEFAULT 0")
    if "archived" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN archived INTEGER NOT NULL DEFAULT 0")
    if "final_evolution" not in columns:
        db.execute("ALTER TABLE individual ADD COLUMN final_evolution TEXT")
    db.commit()
    return db


def import_individuals(db: sqlite3.Connection, items: Iterable[Mapping[str, Any]]) -> int:
    from .localization import normalize_individual

    timestamp = now()
    count = 0
    for raw_item in items:
        item = normalize_individual(dict(raw_item))
        uid = item.get("uid")
        existing = None
        if not uid and item.get("sp") is not None:
            matches = db.execute("SELECT * FROM individual WHERE species=? AND sp=?",
                                 (item["species"], item["sp"])).fetchall()
            if len(matches) == 1:
                existing = matches[0]
                uid = existing["uid"]
        # A later capture may intentionally show only nature/subskills. Never
        # replace previously reviewed fields with OCR placeholders or partial
        # ingredient lists from that complementary video.
        if existing:
            missing = set(raw_item.get("ocr_missing", []))
            if "nature" in missing:
                item["nature"] = existing["nature"]
            if "ingredients" in missing:
                item["ingredients"] = json.loads(existing["ingredients_json"])
            if "subskills" in missing:
                item["subskills"] = json.loads(existing["subskills_json"])
            if "main_skill" in missing:
                item["main_skill"] = existing["main_skill"]
                item["skill_level"] = existing["skill_level"]
        uid = uid or canonical_uid(item)
        same_core = bool(existing and all((
            existing["nature"] == item["nature"],
            json.loads(existing["ingredients_json"]) == item["ingredients"],
            json.loads(existing["subskills_json"]) == item["subskills"],
            existing["main_skill"] == item["main_skill"],
            existing["skill_level"] == item["skill_level"],
        )))
        review_confirmed = bool(item.get("review_confirmed") or
                                (existing and existing["review_confirmed"]))
        verified = bool(review_confirmed or item.get("verified") or
                        (same_core and existing["verified"]))

        def engine_scores(field: str, column: str) -> str:
            """Keep engine output that a capture cannot carry.

            A rescan supplies no score at all, so overwriting would silently
            discard `evaluate` results and force a full recomputation. The
            scores describe the stats they were computed from, so they are only
            preserved while those stats are unchanged.
            """
            value = item.get(field)
            if value:
                return json.dumps(value, ensure_ascii=False)
            if same_core:
                return existing[column]
            return "{}"

        db.execute(
            """INSERT INTO individual
            (uid,species,display_name,level,nature,pokemon_type,berry,energy_scores_json,island_scores_json,ingredients_json,subskills_json,
             main_skill,skill_level,sp,box_index,first_seen,last_seen,confidence,verified,review_confirmed)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            ON CONFLICT(uid) DO UPDATE SET species=excluded.species,display_name=excluded.display_name,
              level=excluded.level,nature=excluded.nature,pokemon_type=excluded.pokemon_type,
              berry=excluded.berry,
              energy_scores_json=excluded.energy_scores_json,
              island_scores_json=excluded.island_scores_json,ingredients_json=excluded.ingredients_json,
              subskills_json=excluded.subskills_json,main_skill=excluded.main_skill,
              skill_level=excluded.skill_level,sp=excluded.sp,box_index=excluded.box_index,
              last_seen=excluded.last_seen,confidence=excluded.confidence,
              review_confirmed=MAX(individual.review_confirmed,excluded.review_confirmed),
              verified=MAX(individual.review_confirmed,excluded.verified,excluded.review_confirmed)""",
            (uid, item["species"], item.get("display_name"), item.get("level"),
             item["nature"], item.get("pokemon_type"),
             item.get("berry"),
             engine_scores("energy_scores", "energy_scores_json"),
             engine_scores("island_scores", "island_scores_json"),
             json.dumps(item["ingredients"], ensure_ascii=False),
             json.dumps(item["subskills"], ensure_ascii=False), item["main_skill"],
             item["skill_level"], item.get("sp"), item.get("box_index"),
             timestamp, timestamp, item.get("confidence", 0.0), verified, review_confirmed),
        )
        for anchor_text, scores in item.get("scores", {}).items():
            for role, score in scores.items():
                if int(anchor_text) in ANCHORS and role in ROLES:
                    db.execute(
                        """INSERT OR REPLACE INTO evaluation VALUES
                        (?,?,?,?,?,?,?,?,?)""",
                        (uid, int(anchor_text), role, float(score), None, None,
                         "imported", "imported", timestamp),
                    )
        count += 1
    db.commit()
    return count


def decide(db: sqlite3.Connection, keep_top_n: int = 2,
           protected_uids: Sequence[str] = (), low_score_threshold: float = 30.0) -> Dict[str, int]:
    people = db.execute("SELECT * FROM individual WHERE archived=0 ORDER BY species, box_index").fetchall()
    scores = {(r["uid"], r["anchor_level"], r["role"]): r["score"] for r in
              db.execute("SELECT uid,anchor_level,role,score FROM evaluation")}
    by_species: Dict[str, List[sqlite3.Row]] = {}
    for person in people:
        by_species.setdefault(person["species"], []).append(person)
    counts = {"keep": 0, "send": 0, "protected": 0}
    timestamp = now()
    for species, group in by_species.items():
        for person in group:
            uid = person["uid"]
            if uid in protected_uids:
                verdict, reason = "protected", "保護リストで指定されています"
            elif not person["verified"]:
                verdict, reason = "protected", "検証が完了していないため判定対象外です"
            elif any((uid, a, r) not in scores for a in ANCHORS for r in ROLES):
                verdict, reason = "protected", "Lv60/Lv80の全ロール評価が未完了です"
            else:
                def peak_role_score(candidate_uid: str) -> Tuple[str, float]:
                    evaluations = {
                        anchor: {role: scores[(candidate_uid, anchor, role)] for role in ROLES}
                        for anchor in ANCHORS
                    }
                    role_scores = absolute_role_scores(evaluations)
                    return max(role_scores.items(), key=lambda item: item[1])

                best_role, best_role_score = peak_role_score(uid)
                better = sum(
                    peak_role_score(other["uid"])[1] > best_role_score
                    for other in group if other["uid"] != uid
                )
                if better >= keep_top_n:
                    verdict = "send"
                    reason = (f"Lv50/60/70/80で最も尖った役割（{best_role}・"
                              f"{best_role_score:.1f}点）を比べても、同種の上位個体が"
                              f"{keep_top_n}匹以上います")
                else:
                    verdict = "keep"
                    reason = (f"Lv50/60/70/80で最も尖った役割（{best_role}・"
                              f"{best_role_score:.1f}点）が同種上位候補です")
            db.execute("INSERT OR REPLACE INTO decision VALUES (?,?,?,?)",
                       (uid, verdict, reason, timestamp))
            counts[verdict] += 1
    db.commit()
    return counts


def load_dashboard(db: sqlite3.Connection) -> List[Dict[str, Any]]:
    from .localization import to_japanese
    rows = db.execute("""SELECT i.*,d.verdict,d.reason FROM individual i
                         LEFT JOIN decision d ON d.uid=i.uid
                         WHERE i.archived=0 ORDER BY i.box_index""").fetchall()
    evaluations: Dict[str, Dict[int, Dict[str, float]]] = {}
    for row in db.execute("SELECT uid,anchor_level,role,score FROM evaluation"):
        evaluations.setdefault(row["uid"], {}).setdefault(row["anchor_level"], {})[row["role"]] = row["score"]
    result = []
    for row in rows:
        item_scores = evaluations.get(row["uid"], {})
        role_scores = absolute_role_scores(item_scores)
        ingredients = json.loads(row["ingredients_json"] or "[]")
        ingredient_slots = [{"name": x[0], "amount": x[1],
                             "base_energy": INGREDIENT_BASE_ENERGY.get(x[0], 0),
                             "drop_energy": x[1] * INGREDIENT_BASE_ENERGY.get(x[0], 0)}
                            for x in ingredients if len(x) >= 2]
        result.append({**dict(row), "species_ja": to_japanese("species", row["species"]),
                       "nature_ja": to_japanese("natures", row["nature"]),
                       "evaluations": item_scores,
                       "island_scores": json.loads(row["island_scores_json"] or "{}"),
                       "energy_scores": json.loads(row["energy_scores_json"] or "{}"),
                       "ingredient_slots": ingredient_slots,
                       "absolute_by_role": role_scores,
                       "absolute_score": max(role_scores.values(), default=0.0),
                       "review_confirmed": bool(row["review_confirmed"])})
    return result


def build_team_plans(items: Sequence[Mapping[str, Any]], team_size: int = 5) -> List[Dict[str, Any]]:
    """Select the exact best additive team for each island and training anchor.

    Island scores must come from the external game engine/input. Missing values
    are excluded instead of estimated in Python.
    """
    islands = sorted({island for item in items for island in item.get("island_scores", {})})
    plans: List[Dict[str, Any]] = []
    for island in islands:
        for mode in ("current", "50", "60", "70", "80"):
            candidates = []
            for item in items:
                if not item.get("verified"):
                    continue
                value = item.get("island_scores", {}).get(island, {}).get(mode)
                if value is not None:
                    candidates.append((float(value), item))
            selected = sorted(candidates, key=lambda pair: (-pair[0], pair[1]["uid"]))[:team_size]
            if selected:
                plans.append({
                    "island": island,
                    "mode": mode,
                    "total_score": round(sum(score for score, _ in selected), 2),
                    "members": [{"uid": item["uid"], "name": item.get("display_name") or item["species"],
                                 "species": item["species"], "type": item.get("pokemon_type"),
                                 "score": score} for score, item in selected],
                })
    return plans


def absolute_role_scores(evaluations: Mapping[int, Mapping[str, float]],
                         references: Mapping = ABSOLUTE_REFERENCES,
                         weights: Mapping[int, float] = ANCHOR_WEIGHTS) -> Dict[str, float]:
    """Return stable 0-100 scores based on fixed references, never box rank."""
    result: Dict[str, float] = {}
    for role in ROLES:
        if any(role not in evaluations.get(anchor, {}) for anchor in ANCHORS):
            result[role] = 0.0
            continue
        ratio = sum(weights[a] * max(0.0, evaluations[a][role]) /
                    float(references[a][role] if a in references else references[role])
                    for a in ANCHORS)
        result[role] = round(min(100.0, ratio * 100.0), 1)
    return result


# Convenience 0-100 cut points for this app's own species tier, chosen to
# roughly match a six-tier external scale (SS/S/A/B/C/D). The score itself is
# the only rigorous part; these letters are just a readable label on top of it.
TIER_CUTS = (("SS", 95.0), ("S", 85.0), ("A", 70.0), ("B", 50.0), ("C", 30.0))


def score_to_tier(score: float) -> str:
    for label, cutoff in TIER_CUTS:
        if score >= cutoff:
            return label
    return "D"


# Snapshot of a third-party Pokémon Sleep tier list, kept only to let users
# sanity-check this app's own 0-100 species score against an independent
# source. Source: https://gamerch.com/pokesleep/787542 (終盤最強 ranking),
# fetched 2026-08-24. Species names are the Japanese names used by that site;
# they are mapped to this app's English species keys via localization.to_english.
EXTERNAL_TIER_JA: Dict[str, str] = {
    **{name: "SS" for name in (
        "サーナイト", "リザードン", "カメックス", "トドゼルガ", "カイリュー",
        "バクフーン", "オーダイル", "メガニウム", "ハガネール")},
    **{name: "S" for name in (
        "ジバコイル", "プクリン", "フシギバナ", "ライチュウ", "ゲンガー", "デリバード",
        "ウツボット", "バンギラス", "キュウコン", "エンテイ", "ライコウ", "スイクン")},
    **{name: "A" for name in (
        "ガルーラ", "グレイシア", "ブースター", "ニンフィア", "バタフリー", "ケッキング",
        "ドードリオ", "デンリュウ", "エーフィ", "ヘラクレス", "ダグトリオ", "ゴローニャ",
        "キテルグマ", "マスカーニャ", "ウェーニバル")},
    **{name: "B" for name in (
        "シャワーズ", "ヘルガー", "サンダース", "ウソッキー", "オコリザル", "ガラガラ",
        "バリヤード", "メタモン", "トゲキッス", "ユキノオー", "キュワワー", "デデンネ",
        "リーフィア", "ピクシー", "ジュペッタ", "ラッタ", "チルタリス", "ラウドボーン")},
    **{name: "C" for name in (
        "エルレイド", "アブソル", "ゴルダック", "カイロス", "ドクロッグ", "ヤドキング",
        "ヤドラン", "ウインディ", "アーボック", "ブラッキー")},
    **{name: "D" for name in (
        "ソーナンス", "ヤミラミ", "マルノーム", "ペルシアン", "ルカリオ")},
}


def compare_species_tiers(species_scores: Mapping[str, Mapping[str, Any]]) -> List[Dict[str, Any]]:
    """Pair this app's own species score against the external tier snapshot.

    `species_scores` maps English species key to {"absolute_score": float, ...},
    as produced by engine.species_scores(). Species missing from either side
    are left out rather than guessed.
    """
    from .localization import to_english, to_japanese

    external_by_key = {to_english("species", ja): tier for ja, tier in EXTERNAL_TIER_JA.items()}
    rows = []
    for key, tier in external_by_key.items():
        own = species_scores.get(key)
        if own is None:
            continue
        rows.append({"species": key, "species_ja": to_japanese("species", key),
                     "our_score": own["absolute_score"], "our_tier": score_to_tier(own["absolute_score"]),
                     "external_tier": tier})
    rows.sort(key=lambda r: -r["our_score"])
    return rows
