from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


CSS = """
:root{color-scheme:light;--bg:#f4f7f3;--surface:#fff;--surface-2:#eef4ef;--ink:#183026;--muted:#64766d;--line:#dce7df;--brand:#267553;--brand-2:#49a574;--brand-soft:#dff2e7;--amber:#d78924;--red:#c95353;--shadow:0 14px 40px rgba(31,71,51,.09)}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -10%,#dcefe3 0,transparent 36rem),var(--bg);color:var(--ink);font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
button,select{font:inherit}button,select{min-height:44px}main{max-width:860px;margin:auto;padding:0 18px 88px}.hero{padding:34px 2px 20px}.eyebrow{color:var(--brand);font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}.hero h1{font-size:clamp(30px,8vw,48px);line-height:1.08;letter-spacing:-.04em;margin:6px 0}.hero p{color:var(--muted);margin:8px 0 0}.tabs{display:flex;gap:5px;position:sticky;top:10px;z-index:10;padding:6px;background:rgba(255,255,255,.9);border:1px solid var(--line);border-radius:16px;box-shadow:0 8px 26px rgba(31,71,51,.08);backdrop-filter:blur(16px)}
.tabs button{flex:1;border:0;border-radius:11px;padding:8px 9px;background:transparent;color:var(--muted);font-size:13px;font-weight:650;cursor:pointer}.tabs button.active{background:var(--ink);color:#fff;box-shadow:0 4px 12px rgba(24,48,38,.2)}
.card{background:var(--surface);border:1px solid rgba(220,231,223,.85);border-radius:22px;padding:20px;margin:14px 0;box-shadow:var(--shadow)}.meta{color:var(--muted);font-size:13px}.send{border-left:5px solid var(--red)}.keep{border-left:5px solid var(--brand-2)}.protected{border-left:5px solid var(--amber)}
h2{font-size:20px;line-height:1.25;margin:4px 0 8px;letter-spacing:-.02em}h3{margin:0;font-size:16px}small{font-size:12px;color:var(--brand);white-space:nowrap}.control-title{display:flex;align-items:center;gap:10px;margin-bottom:15px}.control-title .icon{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--brand-soft);font-size:20px}.field{display:grid;gap:6px}.field>span{font-size:12px;font-weight:700;color:var(--muted)}select{width:100%;appearance:none;border:1px solid var(--line);border-radius:13px;padding:10px 36px 10px 12px;color:var(--ink);background:var(--surface) url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%2364766d' stroke-width='2'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E") no-repeat right 11px center}.berry-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:12px 0}.berry-field{padding:10px;background:var(--surface-2);border-radius:15px}.berry-field select{border:0;background-color:transparent;padding-left:2px;font-weight:700}.mode-row{display:grid;grid-template-columns:1.4fr 1fr;gap:12px;align-items:end;margin-top:12px}.hint{color:var(--muted);font-size:12px;margin:7px 0 0}
.team-head{display:flex;justify-content:space-between;align-items:end;margin:22px 2px 8px}.team-head strong{font-size:26px;line-height:1}.team-list{display:grid;gap:10px}.member{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:12px;align-items:center;background:var(--surface);border:1px solid var(--line);border-radius:18px;padding:13px 15px;box-shadow:0 7px 22px rgba(31,71,51,.06)}.rank{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--surface-2);font-weight:800;color:var(--muted)}.member:first-child{border-color:#e8c778;background:linear-gradient(110deg,#fffdf4,#fff)}.member:first-child .rank{background:#f5d87e;color:#674b00}.member-name{font-size:16px;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tags{display:flex;gap:5px;flex-wrap:wrap}.tag{font-size:11px;color:var(--muted);background:var(--surface-2);padding:3px 7px;border-radius:999px}.tag.favorite{color:#16613f;background:var(--brand-soft)}.power{text-align:right}.power strong{display:block;font-size:18px}.power span{font-size:10px;color:var(--muted);letter-spacing:.08em}.empty{text-align:center;padding:42px 18px;color:var(--muted)}
.dex-tools{display:grid;grid-template-columns:minmax(0,1fr) 170px;gap:10px;margin:18px 0 12px}.search{min-height:46px;width:100%;border:1px solid var(--line);border-radius:14px;padding:10px 14px 10px 42px;color:var(--ink);background:var(--surface) url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='%2364766d' stroke-width='2'%3E%3Ccircle cx='11' cy='11' r='8'/%3E%3Cpath d='m21 21-4.3-4.3'/%3E%3C/svg%3E") no-repeat 14px center;font:inherit}.dex-summary{display:flex;justify-content:space-between;align-items:end;margin:18px 2px 8px}.dex-summary strong{font-size:26px}.dex-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.poke-card{display:grid;grid-template-columns:50px minmax(0,1fr) auto;gap:12px;align-items:center;background:var(--surface);border:1px solid var(--line);border-radius:18px;padding:14px;box-shadow:0 7px 22px rgba(31,71,51,.06)}.poke-avatar{display:grid;place-items:center;width:50px;height:50px;border-radius:16px;background:linear-gradient(145deg,var(--brand-soft),var(--surface-2));color:var(--brand);font-size:19px;font-weight:800;text-transform:uppercase}.poke-title{font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.poke-sub{color:var(--muted);font-size:12px}.rating{display:grid;place-items:center;width:46px;height:46px;border:4px solid var(--brand-soft);border-top-color:var(--brand);border-radius:50%;font-weight:800;font-size:13px}.type-grass{--brand-soft:#dff3df;--brand:#398849}.type-water{--brand-soft:#dcecf8;--brand:#347eb1}.type-fire{--brand-soft:#fde6da;--brand:#c86434}.type-electric{--brand-soft:#fff1bd;--brand:#a47600}.type-psychic{--brand-soft:#f6deeb;--brand:#a85581}.type-fairy{--brand-soft:#f6e1ef;--brand:#a95789}.type-ice{--brand-soft:#dff5f5;--brand:#32858a}.type-dragon{--brand-soft:#e6e1f8;--brand:#6755a8}.type-ghost{--brand-soft:#e7e3f0;--brand:#685d88}.type-dark{--brand-soft:#e5e1df;--brand:#685b54}
.guide-intro{margin:22px 2px}.guide-intro h2{font-size:28px}.guide-list{display:grid;gap:11px;counter-reset:guide}.guide-step{counter-increment:guide;display:grid;grid-template-columns:46px minmax(0,1fr);gap:14px;align-items:start;background:var(--surface);border:1px solid var(--line);border-radius:19px;padding:17px;box-shadow:0 7px 22px rgba(31,71,51,.06)}.guide-step:before{content:counter(guide);display:grid;place-items:center;width:42px;height:42px;border-radius:14px;background:var(--brand-soft);color:var(--brand);font-size:18px;font-weight:800}.guide-step p{color:var(--muted);margin:5px 0 0}.guide-note{display:grid;grid-template-columns:36px 1fr;gap:10px;margin-top:14px;padding:15px;border-radius:16px;background:var(--brand-soft);color:var(--ink)}.guide-note strong{display:block}.guide-note span{font-size:13px;color:var(--muted)}
.scores{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.score{padding:9px;background:var(--surface-2);border-radius:11px;text-align:center;font-size:12px}.score strong{font-size:16px}.scoreline{height:5px;margin-top:12px;border-radius:5px;background:var(--line);overflow:hidden}.scoreline i{display:block;height:100%;background:linear-gradient(90deg,var(--brand),#68be8d);border-radius:inherit}
.island-grid,.insight-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:16px}.energy-number{font-size:25px;font-weight:800;letter-spacing:-.03em}.energy-range{color:var(--muted);font-size:12px}.mode-pills{display:flex;gap:6px;overflow:auto;margin:12px 0}.mode-pills button{border:1px solid var(--line);background:var(--surface-2);border-radius:999px;padding:5px 11px;min-height:34px;white-space:nowrap}.mode-pills button.active{background:var(--brand);color:white}.diagnosis{display:inline-block;padding:4px 9px;border-radius:99px;background:var(--brand-soft);color:var(--brand);font-size:12px;font-weight:700}.capture-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;padding:12px 0;border-bottom:1px solid var(--line)}.capture-row:last-child{border:0}.bar{height:8px;background:var(--line);border-radius:9px;overflow:hidden;margin-top:7px}.bar i{display:block;height:100%;background:var(--brand);border-radius:inherit}.quality{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.quality div{text-align:center;background:var(--surface-2);border-radius:12px;padding:10px 5px}.quality strong{display:block;font-size:21px}.goal-box{display:grid;grid-template-columns:1fr 1fr;gap:10px;align-items:end}.goal-box input{width:100%;min-height:44px;border:1px solid var(--line);border-radius:12px;padding:9px;background:var(--surface);color:var(--ink)}
@media(max-width:600px){main{padding-inline:12px}.hero{padding-top:24px}.tabs{position:fixed;inset:auto 10px 10px;top:auto;border-radius:18px;overflow-x:auto}.tabs button{font-size:10px;padding-inline:8px;min-width:58px}.card{padding:16px;border-radius:19px}.berry-grid{grid-template-columns:1fr}.berry-field{display:grid;grid-template-columns:64px 1fr;align-items:center}.mode-row,.dex-tools,.goal-box{grid-template-columns:1fr}.scores{grid-template-columns:repeat(2,1fr)}.member{grid-template-columns:38px minmax(0,1fr) auto;padding:12px 11px;gap:9px}.rank{width:34px;height:34px}.power strong{font-size:16px}.dex-grid,.island-grid,.insight-grid{grid-template-columns:1fr}.quality{grid-template-columns:repeat(2,1fr)}}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#0f1914;--surface:#17231d;--surface-2:#202f27;--ink:#eef7f1;--muted:#9bafa4;--line:#2b4035;--brand:#65c493;--brand-2:#54ae7e;--brand-soft:#1d3b2c;--shadow:0 14px 40px rgba(0,0,0,.2)}body{background:radial-gradient(circle at 50% -10%,#1b3829 0,transparent 34rem),var(--bg)}.tabs{background:rgba(23,35,29,.9)}.tabs button.active{background:#eef7f1;color:#132219}.member:first-child{background:linear-gradient(110deg,#292819,var(--surface));border-color:#685d32}.member:first-child .rank{background:#5c4f20;color:#ffe89d}}
"""


def render_site(items: List[Dict[str, Any]], out: Path, teams: Optional[List[Dict[str, Any]]] = None,
                insights: Optional[Dict[str, Any]] = None) -> None:
    out.mkdir(parents=True, exist_ok=True)
    safe = []
    for item in items:
        safe.append({k: item.get(k) for k in ("uid", "species", "species_ja", "display_name", "level", "box_index", "verdict", "reason", "evaluations", "absolute_score", "absolute_by_role", "pokemon_type", "berry", "production_scores", "energy_scores", "confidence", "verified", "sp", "sp_diff", "nature_ja", "main_skill", "skill_level", "ingredients_json", "subskills_json")})
    data = json.dumps(safe, ensure_ascii=False).replace("</", "<\\/")
    team_data = json.dumps(teams or [], ensure_ascii=False).replace("</", "<\\/")
    insight_data = json.dumps(insights or {}, ensure_ascii=False).replace("</", "<\\/")
    page = f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sleepbox Compass</title><style>{CSS}</style></head>
<body><main><header class="hero"><div class="eyebrow">Pokémon Sleep Box Planner</div><h1>Sleepbox<br>Compass</h1><p>今週のきのみから、いちばん強い5匹へ。</p></header><nav class="tabs" aria-label="メインメニュー"><button data-tab="energy">島予測</button><button data-tab="capture">捕獲</button><button data-tab="analysis">分析</button><button data-tab="teams">編成</button><button data-tab="pokemon">一覧</button><button data-tab="keep">育成</button><button data-tab="send">整理</button><button data-tab="guide">使い方</button></nav><section id="list" aria-live="polite"></section></main>
<script>const DATA={data};const TEAMS={team_data};const INSIGHTS={insight_data};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
const BERRIES={{PAMTRE:'シーヤ',LUM:'ラム',GREPA:'ウブ',BLUK:'ブリー',PECHA:'モモン',MAGO:'マゴ',LEPPA:'ヒメリ',CHERI:'クラボ',PERSIM:'キー',FIGY:'フィラ',DURIN:'ドリ',SITRUS:'オボン',ORAN:'オレン',WIKI:'ウイ',CHESTO:'カゴ',RAWST:'チーゴ',BELUE:'ベリブ',YACHE:'ヤチェ'}};
const ISLANDS={{custom:{{name:'自由選択',berries:[]}},greengrass:{{name:'ワカクサ本島（ランダム）',berries:[]}},cyan:{{name:'シアンの砂浜',berries:['ORAN','PAMTRE','PECHA']}},taupe:{{name:'トープ洞窟',berries:['FIGY','LEPPA','SITRUS']}},snowdrop:{{name:'ウノハナ雪原',berries:['PERSIM','RAWST','WIKI']}},lapis:{{name:'ラピスラズリ湖畔',berries:['CHERI','DURIN','MAGO']}},powerplant:{{name:'ゴールド旧発電所',berries:['BELUE','BLUK','GREPA']}},amber:{{name:'アンバー渓谷',berries:['CHESTO','LUM','YACHE']}}}};
const options=o=>Object.entries(o).map(([v,n])=>`<option value="${{v}}">${{esc(n.name||n)}}</option>`).join('');
function teamControls(){{return `<article class="card"><div class="control-title"><span class="icon">🏝️</span><div><h2>フィールド設定</h2><div class="meta">島を選ぶときのみが自動で入ります</div></div></div><label class="field"><span>島・フィールド</span><select id="island">${{options(ISLANDS)}}</select></label><div class="berry-grid">${{[0,1,2].map(i=>`<label class="berry-field field"><span>きのみ ${{i+1}}</span><select class="berry">${{options(BERRIES)}}</select></label>`).join('')}}</div><div class="mode-row"><label class="field"><span>評価する育成段階</span><select id="team-mode"><option value="current">現在のレベル</option>${{[50,60,70,80].map(x=>`<option value="${{x}}">Lv${{x}}まで育成</option>`).join('')}}</select></label><p class="hint">きのみを直接変えると自由選択になります</p></div></article><section id="team-result"></section>`}}
function updateTeam(){{const favored=[...document.querySelectorAll('.berry')].map(x=>x.value),mode=document.querySelector('#team-mode').value,island=ISLANDS[document.querySelector('#island').value];const ranked=DATA.map(x=>{{const p=x.production_scores?.[mode],energy=island?.name&&x.energy_scores?.[island.name]?.[mode],favorite=favored.includes(x.berry),score=p?Number(p.total)+(favorite?Number(p.berry):0):Number(energy?.expected||0);if(!score)return null;return {{...x,favorite,teamScore:Math.round(score)}}}}).filter(Boolean).sort((a,b)=>b.teamScore-a.teamScore).slice(0,5),total=Math.round(ranked.reduce((s,x)=>s+x.teamScore,0)),max=Math.max(...ranked.map(x=>x.teamScore),1);document.querySelector('#team-result').innerHTML=`<div class="guide-note"><div>🧪</div><div><strong>暫定計算</strong><span>性格・食材の確認前は参考値です。整理判定には使いません。</span></div></div><div class="team-head"><div><div class="eyebrow">Recommended team</div><h2>${{mode==='current'?'いまの最強5匹':`Lv${{mode}} 育成後`}}</h2></div><div class="power"><span>TEAM ENERGY / DAY</span><strong>${{fmt(total)}}</strong></div></div>${{ranked.length?`<div class="team-list">${{ranked.map((x,i)=>`<article class="member"><div class="rank">${{i+1}}</div><div><div class="member-name">${{esc(x.display_name||x.species_ja||x.species)}}</div><div class="tags"><span class="tag">${{esc(x.verified?'検証済':'暫定')}}</span><span class="tag ${{x.favorite?'favorite':''}}">${{x.favorite?'★ ':''}}${{BERRIES[x.berry]||x.berry||'きのみ未登録'}}</span></div><div class="scoreline"><i style="width:${{Math.round(x.teamScore/max*100)}}%"></i></div></div><div class="power"><span>ENERGY</span><strong>${{fmt(x.teamScore)}}</strong></div></article>`).join('')}}</div>`:'<div class="card empty">固定島を選ぶと、島別エナジーから編成します。</div>'}}`}}
const updateTeamAdditive=updateTeam;updateTeam=function(){{const mode=document.querySelector('#team-mode').value,island=ISLANDS[document.querySelector('#island').value],plan=TEAMS.find(x=>x.island===island?.name&&String(x.mode)===mode&&x.total_energy!=null);if(!plan)return updateTeamAdditive();const rows=plan.members.map(m=>({{...DATA.find(x=>x.uid===m.uid),...m}})),max=Math.max(...rows.map(x=>x.marginal||0),1);document.querySelector('#team-result').innerHTML=`<div class="guide-note"><div>🤝</div><div><strong>チーム相互作用込み</strong><span>元気回復・おてつだい支援・全体効果スキル・発動済みサブスキルを5匹同時に計算。料理は除外しています。</span></div></div><div class="team-head"><div><div class="eyebrow">Recommended team</div><h2>${{mode==='current'?'いまの最強5匹':`Lv${{mode}} 育成後`}}</h2><div class="meta">相互作用差分 ${{plan.synergy_gain>=0?'+':''}}${{fmt(plan.synergy_gain)}}/日 · ${{plan.provisional?'暫定データを含む':'検証済み'}}</div></div><div class="power"><span>TEAM ENERGY / DAY</span><strong>${{fmt(plan.total_energy)}}</strong></div></div><div class="team-list">${{rows.map((x,i)=>`<article class="member"><div class="rank">${{i+1}}</div><div><div class="member-name">${{esc(x.display_name||x.species_ja||x.species||x.uid)}}</div><div class="tags"><span class="tag">${{x.verified?'検証済':'暫定'}}</span>${{Number(x.recovery)>0?`<span class="tag">元気回復 ${{fmt(x.recovery)}}</span>`:''}}${{Number(x.team_help_support)>0?`<span class="tag">支援 ${{fmt(x.team_help_support)}}回</span>`:''}}${{(x.subskills||[]).includes('Helping Bonus')?'<span class="tag">おてつだいボーナス</span>':''}}</div><div class="scoreline"><i style="width:${{Math.round((x.marginal||0)/max*100)}}%"></i></div></div><div class="power"><span>限界貢献</span><strong>${{fmt(x.marginal)}}</strong></div></article>`).join('')}}</div>`}};
const TYPE_KEYS={{'くさ':'grass','みず':'water','ほのお':'fire','でんき':'electric','エスパー':'psychic','フェアリー':'fairy','こおり':'ice','ドラゴン':'dragon','ゴースト':'ghost','あく':'dark'}};
function pokemonControls(){{const types=[...new Set(DATA.map(x=>x.pokemon_type).filter(Boolean))].sort();return `<div class="dex-tools"><input id="poke-search" class="search" type="search" placeholder="名前・種族で検索" aria-label="ポケモン検索"><label class="field"><span>タイプ</span><select id="type-filter"><option value="">すべて</option>${{types.map(x=>`<option>${{esc(x)}}</option>`).join('')}}</select></label></div><div class="dex-summary"><div><div class="eyebrow">Your Pokémon</div><h2>ポケモン一覧</h2></div><div><strong id="poke-count">0</strong><span class="meta"> 匹</span></div></div><p class="meta">総合点はLv50/60/70/80を加重し、きのみ・食材・スキルのうち最も得意な役割を採用。100点は全最終進化種の理想個体上位10%相当です。</p><section id="poke-grid" class="dex-grid"></section>`}}
function updatePokemonList(){{const q=document.querySelector('#poke-search').value.trim().toLowerCase(),type=document.querySelector('#type-filter').value;const rows=DATA.filter(x=>!q||`${{x.display_name||''}} ${{x.species_ja||''}} ${{x.species}}`.toLowerCase().includes(q)).filter(x=>!type||x.pokemon_type===type).sort((a,b)=>(b.absolute_score||0)-(a.absolute_score||0));document.querySelector('#poke-count').textContent=rows.length;document.querySelector('#poke-grid').innerHTML=rows.length?rows.map(x=>{{const name=x.display_name||x.species_ja||x.species,typeKey=TYPE_KEYS[x.pokemon_type]||'',initial=[...name][0]||'?';return `<article class="poke-card type-${{typeKey}}"><div class="poke-avatar" aria-hidden="true">${{esc(initial)}}</div><div><div class="poke-title">${{esc(name)}}</div><div class="poke-sub">Lv${{x.level??'-'}} · SP ${{fmt(x.sp)}} · ${{esc(x.nature_ja||'性格未確認')}}</div><div class="tags"><span class="tag">${{BERRIES[x.berry]||x.berry||'きのみ未登録'}}</span><span class="tag">BOX ${{x.box_index??'-'}}</span><span class="tag">${{x.verified?'検証済':'暫定データ'}}</span></div></div><div class="rating" aria-label="${{x.verified?`総合評価 ${{x.absolute_score??0}}点`:'未検証の暫定値'}}">${{x.verified?(x.absolute_score??0):'暫定'}}</div></article>`}}).join(''):'<div class="card empty">条件に合うポケモンはいません。</div>'}}
function guidePage(){{return `<section class="guide-intro"><div class="eyebrow">How to use</div><h2>Sleepbox Compassの使い方</h2><p class="meta">手持ちを安全に整理し、今週育てる5匹を見つけます。</p></section><div class="guide-list"><article class="guide-step"><div><h3>手持ちデータを取り込む</h3><p>詳細画面の情報をJSONとして取り込みます。画像・動画・個人DBは公開リポジトリへ送信されず、ローカルにだけ保存されます。</p></div></article><article class="guide-step"><div><h3>島と好みのきのみを選ぶ</h3><p>「パーティ」で島を選ぶと固定きのみ3種が自動設定されます。ワカクサ本島では、その週に表示された3種を選んでください。</p></div></article><article class="guide-step"><div><h3>育成段階を切り替える</h3><p>現在、Lv50、Lv60、Lv70、Lv80を切り替えると、その時点で最も強い5匹とチーム合計がすぐ更新されます。</p></div></article><article class="guide-step"><div><h3>育成と整理を判断する</h3><p>「育成」は総合評価の高い候補、「送る」は全レベル・全ロールで同種上位に劣る候補です。未検証個体は安全のため送る候補になりません。</p></div></article></div><div class="guide-note"><div>🔒</div><div><strong>プライバシー優先</strong><span>スクリーンショット、動画、SQLite、ローカル設定はGitHubへ公開されません。</span></div></div>`}}
const fmt=n=>Number(n||0).toLocaleString('ja-JP');let energyMode='current';
function energyPage(){{const fs=INSIGHTS.forecasts||[],provisional=fs.some(f=>f.modes?.[energyMode]?.provisional);return `<section class="guide-intro"><div class="eyebrow">Cooking-free forecast</div><h2>島別エナジー予測</h2><p class="meta">料理を除き、きのみと直接エナジースキルだけを集計。ワカクサ本島は対象外です。</p></section>${{provisional?'<div class="guide-note"><div>🧪</div><div><strong>暫定シミュレーション</strong><span>未確認の性格・食材を仮定した参考値です。確認後に自動で正式値へ更新します。</span></div></div>':''}}<div class="mode-pills">${{[['current','現在'],['50','Lv50'],['60','Lv60'],['70','Lv70'],['80','Lv80']].map(([v,n])=>`<button data-energy-mode="${{v}}" class="${{v===energyMode?'active':''}}">${{n}}</button>`).join('')}}</div><div class="island-grid">${{fs.map(f=>{{const x=f.modes?.[energyMode],d=x?.daily||{{}};return `<article class="card"><span class="diagnosis">${{esc(f.diagnosis)}}</span><h2>${{esc(f.island)}}</h2><div class="meta">フィールドボーナス +${{f.area_bonus}}%</div>${{x?`<div class="energy-number">1日 ${{fmt(d.expected)}}</div><div class="energy-range">安定 ${{fmt(d.low)}}〜上振れ ${{fmt(d.high)}} · 週 ${{fmt(x.weekly.expected)}}</div><div class="bar"><i style="width:${{Math.min(100,d.expected/150000*100)}}%"></i></div><p class="meta">きのみ ${{fmt(d.berry)}}　直接スキル ${{fmt(d.skill)}}</p><div class="tags">${{x.members.map(m=>`<span class="tag">${{esc(m.name)}} ${{fmt(m.energy)}}</span>`).join('')}}</div>`:'<div class="empty">非料理エナジーを取り込むと表示します</div>'}}${{energyMode==='60'?`<p><strong>現在から週 +${{fmt(f.growth_to_60)}}</strong></p>`:''}}</article>`}}).join('')}}</div>`}}
function capturePage(){{const c=INSIGHTS.capture||{{general:[],tailored:[]}},section=(title,sub,rows)=>`<section class="card"><div class="eyebrow">Capture guide</div><h2>${{title}}</h2><p class="meta">${{sub}}</p>${{rows.some(x=>x.sample)?'<div class="guide-note"><div>🧪</div><div><strong>公開デモ</strong><span>ここに表示される数値は架空のサンプルです。</span></div></div>':''}}${{rows.length?rows.map(x=>`<div class="capture-row"><div><strong>${{esc(x.species)}}</strong><div class="meta">${{esc(x.island)}} · ${{esc(x.reason)}}</div></div><strong>${{fmt(x.daily)}}/日</strong></div>`).join(''):'<div class="empty">Neroli’s Labで種族ベンチマークを生成すると表示します。</div>'}}</section>`;return `<section class="guide-intro"><div class="eyebrow">What to catch next</div><h2>次に捕獲するポケモン</h2><p class="meta">理想個体の一般ランキングと、今の手持ちの島別不足を分けて表示します。</p></section>${{section('今の手持ちで優先', '未所持または理想値の80%未満で、弱い島への改善量が大きい候補',c.tailored)}}${{section('一般的な最強候補', 'Lv60理想個体・料理なしの島別上位',c.general)}}`}}
function analysisPage(){{const q=INSIGHTS.quality||{{}},growth=INSIGHTS.growth||[],coverage=INSIGHTS.coverage||[];return `<section class="guide-intro"><div class="eyebrow">Box intelligence</div><h2>育成・汎用性・目標分析</h2></section><article class="card"><h2>データ品質</h2><div class="quality"><div><strong>${{q.total||0}}</strong><span>総数</span></div><div><strong>${{q.verified||0}}</strong><span>検証済</span></div><div><strong>${{q.unverified||0}}</strong><span>未検証</span></div><div><strong>${{q.low_confidence||0}}</strong><span>低信頼</span></div></div></article><article class="card"><h2>目標到達・週途中の立て直し</h2><div class="goal-box"><label class="field"><span>目標エナジー</span><input id="goal-energy" type="number" value="1000000"></label><label class="field"><span>現在のエナジー</span><input id="current-energy" type="number" value="0"></label><label class="field"><span>残り日数</span><input id="days-left" type="number" min="1" max="7" value="7"></label><label class="field"><span>島</span><select id="goal-island">${{(INSIGHTS.forecasts||[]).map((x,i)=>`<option value="${{i}}">${{esc(x.island)}}</option>`).join('')}}</select></label></div><p id="goal-result" class="energy-number"></p></article><div class="insight-grid"><article class="card"><h2>Lv60育成効果</h2>${{growth.slice(0,8).map(x=>`<div class="capture-row"><div><strong>${{esc(x.name)}}</strong><div class="meta">${{esc(x.island)}} · ${{x.reasons.map(esc).join('／')}}</div></div><strong>週 +${{fmt(x.weekly_gain)}}</strong></div>`).join('')||'<div class="empty">差分データがありません</div>'}}</article><article class="card"><h2>全島汎用性</h2>${{coverage.slice(0,8).map(x=>`<div class="capture-row"><div><strong>${{esc(x.name)}}</strong><div class="meta">${{x.islands.map(esc).join('・')||'上位編成なし'}}</div></div><strong>${{x.count}}島</strong></div>`).join('')}}</article></div>`}}
function updateGoal(){{const i=+document.querySelector('#goal-island').value,target=+document.querySelector('#goal-energy').value,current=+document.querySelector('#current-energy').value,days=+document.querySelector('#days-left').value,f=(INSIGHTS.forecasts||[])[i],daily=f?.modes?.current?.daily?.expected||0,need=Math.max(0,target-current),eta=daily?Math.ceil(need/daily):0,projected=current+daily*days,short=Math.max(0,target-projected);document.querySelector('#goal-result').textContent=daily?(short?`到達まで約${{eta}}日 · 期限時点で ${{fmt(short)}}不足見込み`:`約${{eta}}日で到達 · 期限内に ${{fmt(projected-target)}}余裕`):'エナジーデータがありません'}}
function draw(tab){{document.querySelectorAll('[data-tab]').forEach(b=>{{const active=b.dataset.tab===tab;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')}});if(tab==='energy'){{document.querySelector('#list').innerHTML=energyPage();document.querySelectorAll('[data-energy-mode]').forEach(b=>b.onclick=()=>{{energyMode=b.dataset.energyMode;draw('energy')}});return}}if(tab==='capture'){{document.querySelector('#list').innerHTML=capturePage();return}}if(tab==='analysis'){{document.querySelector('#list').innerHTML=analysisPage();document.querySelectorAll('#goal-energy,#goal-island').forEach(x=>x.oninput=updateGoal);updateGoal();return}}if(tab==='teams'){{document.querySelector('#list').innerHTML=teamControls();const bs=[...document.querySelectorAll('.berry')];document.querySelector('#island').value='cyan';bs.forEach((x,i)=>x.value=ISLANDS.cyan.berries[i]);document.querySelector('#island').onchange=e=>{{const preset=ISLANDS[e.target.value].berries;if(preset.length)bs.forEach((x,i)=>x.value=preset[i]);updateTeam()}};bs.forEach(x=>x.onchange=()=>{{document.querySelector('#island').value='custom';updateTeam()}});document.querySelector('#team-mode').onchange=updateTeam;updateTeam();return}}if(tab==='pokemon'){{document.querySelector('#list').innerHTML=pokemonControls();document.querySelector('#poke-search').oninput=updatePokemonList;document.querySelector('#type-filter').onchange=updatePokemonList;updatePokemonList();return}}if(tab==='guide'){{document.querySelector('#list').innerHTML=guidePage();return}}const xs=DATA.filter(x=>tab==='send'?['send','protected'].includes(x.verdict):(x.verdict||'protected')===tab).sort((a,b)=>(b.absolute_score||0)-(a.absolute_score||0));document.querySelector('#list').innerHTML=xs.length?xs.map(x=>{{const e=x.evaluations||{{}};const best=l=>Math.max(...Object.values(e[l]||{{0:0}}));return `<article class="card ${{x.verdict||tab}}"><div class="meta">BOX ${{x.box_index??'-'}} · Lv${{x.level??'-'}}</div><h2>${{esc(x.display_name||x.species_ja||x.species)}} <small>${{x.verified?`${{x.absolute_score??0}} / 100`:'暫定評価'}}</small></h2><p>${{esc(x.reason)}}</p><div class="scores">${{['50','60','70','80'].map(l=>`<div class="score">Lv${{l}}<br><strong>${{Math.round(best(l))}}</strong></div>`).join('')}}</div><p class="meta">きのみ ${{x.absolute_by_role?.berry??0}}　食材 ${{x.absolute_by_role?.ingredient??0}}　スキル ${{x.absolute_by_role?.skill??0}}</p></article>`}}).join(''):'<div class="card empty">該当する個体はいません。</div>'}}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>draw(b.dataset.tab));const hasForecast=(INSIGHTS.forecasts||[]).some(x=>x.modes&&Object.keys(x.modes).length);draw(hasForecast?'energy':'pokemon');</script></body></html>'''
    (out / "index.html").write_text(page, encoding="utf-8")
    (out / ".nojekyll").write_text("", encoding="utf-8")
