from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any, Dict, List, Optional


CSS = """
:root{color-scheme:light;--bg:#f4f7f3;--surface:#fff;--surface-2:#eef4ef;--ink:#183026;--muted:#64766d;--line:#dce7df;--brand:#267553;--brand-2:#49a574;--brand-soft:#dff2e7;--amber:#d78924;--red:#c95353;--shadow:0 14px 40px rgba(31,71,51,.09)}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -10%,#dcefe3 0,transparent 36rem),var(--bg);color:var(--ink);font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
button,select{font:inherit}button,select{min-height:44px}main{max-width:860px;margin:auto;padding:0 18px 88px}.hero{padding:34px 2px 20px}.eyebrow{color:var(--brand);font-size:12px;font-weight:700;letter-spacing:.14em;text-transform:uppercase}.hero h1{font-size:clamp(30px,8vw,48px);line-height:1.08;letter-spacing:-.04em;margin:6px 0}.hero p{color:var(--muted);margin:8px 0 0}.tabs{display:flex;gap:5px;position:sticky;top:10px;z-index:10;padding:6px;background:rgba(255,255,255,.9);border:1px solid var(--line);border-radius:16px;box-shadow:0 8px 26px rgba(31,71,51,.08);backdrop-filter:blur(16px)}
.tabs button{flex:1;border:0;border-radius:11px;padding:8px 9px;background:transparent;color:var(--muted);font-size:13px;font-weight:650;cursor:pointer}.tabs button.active{background:var(--ink);color:#fff;box-shadow:0 4px 12px rgba(24,48,38,.2)}
.card{background:var(--surface);border:1px solid rgba(220,231,223,.85);border-radius:22px;padding:20px;margin:14px 0;box-shadow:var(--shadow)}.meta{color:var(--muted);font-size:13px}.send{border-left:5px solid var(--red)}.keep{border-left:5px solid var(--brand-2)}.protected{border-left:5px solid var(--amber)}
h2{font-size:20px;line-height:1.25;margin:4px 0 8px;letter-spacing:-.02em}h3{margin:0;font-size:16px}small{font-size:12px;color:var(--brand);white-space:nowrap}.control-title{display:flex;align-items:center;gap:10px;margin-bottom:15px}.control-title .icon{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--brand-soft);font-size:20px}.field{display:grid;gap:6px}.field>span{font-size:12px;font-weight:700;color:var(--muted)}select{width:100%;appearance:none;border:1px solid var(--line);border-radius:13px;padding:10px 36px 10px 12px;color:var(--ink);background:var(--surface) url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%2364766d' stroke-width='2'%3E%3Cpath d='m6 9 6 6 6-6'/%3E%3C/svg%3E") no-repeat right 11px center}.berry-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:12px 0}.berry-field{padding:10px;background:var(--surface-2);border-radius:15px}.berry-field select{border:0;background-color:transparent;padding-left:2px;font-weight:700}.mode-row{display:grid;grid-template-columns:1.4fr 1fr;gap:12px;align-items:end;margin-top:12px}.hint{color:var(--muted);font-size:12px;margin:7px 0 0}
.team-head{display:flex;justify-content:space-between;align-items:end;margin:22px 2px 8px}.team-head strong{font-size:26px;line-height:1}.team-list{display:grid;gap:10px}.member{display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:12px;align-items:center;background:var(--surface);border:1px solid var(--line);border-radius:18px;padding:13px 15px;box-shadow:0 7px 22px rgba(31,71,51,.06)}.rank{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--surface-2);font-weight:800;color:var(--muted)}.member:first-child{border-color:#e8c778;background:linear-gradient(110deg,#fffdf4,#fff)}.member:first-child .rank{background:#f5d87e;color:#674b00}.member-name{font-size:16px;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tags{display:flex;gap:5px;flex-wrap:wrap}.tag{font-size:11px;color:var(--muted);background:var(--surface-2);padding:3px 7px;border-radius:999px}.tag.favorite{color:#16613f;background:var(--brand-soft)}.power{text-align:right}.power strong{display:block;font-size:18px}.power span{font-size:10px;color:var(--muted);letter-spacing:.08em}.empty{text-align:center;padding:42px 18px;color:var(--muted)}
.scores{display:grid;grid-template-columns:repeat(4,1fr);gap:7px}.score{padding:9px;background:var(--surface-2);border-radius:11px;text-align:center;font-size:12px}.score strong{font-size:16px}.scoreline{height:5px;margin-top:12px;border-radius:5px;background:var(--line);overflow:hidden}.scoreline i{display:block;height:100%;background:linear-gradient(90deg,var(--brand),#68be8d);border-radius:inherit}
@media(max-width:600px){main{padding-inline:12px}.hero{padding-top:24px}.tabs{position:fixed;inset:auto 10px 10px;top:auto;border-radius:18px}.tabs button{font-size:11px;padding-inline:4px}.card{padding:16px;border-radius:19px}.berry-grid{grid-template-columns:1fr}.berry-field{display:grid;grid-template-columns:64px 1fr;align-items:center}.mode-row{grid-template-columns:1fr}.scores{grid-template-columns:repeat(2,1fr)}.member{grid-template-columns:38px minmax(0,1fr) auto;padding:12px 11px;gap:9px}.rank{width:34px;height:34px}.power strong{font-size:16px}}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--bg:#0f1914;--surface:#17231d;--surface-2:#202f27;--ink:#eef7f1;--muted:#9bafa4;--line:#2b4035;--brand:#65c493;--brand-2:#54ae7e;--brand-soft:#1d3b2c;--shadow:0 14px 40px rgba(0,0,0,.2)}body{background:radial-gradient(circle at 50% -10%,#1b3829 0,transparent 34rem),var(--bg)}.tabs{background:rgba(23,35,29,.9)}.tabs button.active{background:#eef7f1;color:#132219}.member:first-child{background:linear-gradient(110deg,#292819,var(--surface));border-color:#685d32}.member:first-child .rank{background:#5c4f20;color:#ffe89d}}
"""


def render_site(items: List[Dict[str, Any]], out: Path, teams: Optional[List[Dict[str, Any]]] = None) -> None:
    out.mkdir(parents=True, exist_ok=True)
    safe = []
    for item in items:
        safe.append({k: item.get(k) for k in ("uid", "species", "display_name", "level", "box_index", "verdict", "reason", "evaluations", "absolute_score", "absolute_by_role", "pokemon_type", "berry", "production_scores")})
    data = json.dumps(safe, ensure_ascii=False).replace("</", "<\\/")
    team_data = json.dumps(teams or [], ensure_ascii=False).replace("</", "<\\/")
    page = f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sleepbox Compass</title><style>{CSS}</style></head>
<body><main><header class="hero"><div class="eyebrow">Pokémon Sleep Box Planner</div><h1>Sleepbox<br>Compass</h1><p>今週のきのみから、いちばん強い5匹へ。</p></header><nav class="tabs" aria-label="メインメニュー"><button data-tab="teams">最強パーティ</button><button data-tab="keep">育成</button><button data-tab="send">送る</button><button data-tab="protected">保護</button></nav><section id="list" aria-live="polite"></section></main>
<script>const DATA={data};const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
const BERRIES={{PAMTRE:'シーヤ',LUM:'ラム',GREPA:'ウブ',BLUK:'ブリー',PECHA:'モモン',MAGO:'マゴ',LEPPA:'ヒメリ',CHERI:'クラボ',PERSIM:'キー',FIGY:'フィラ',DURIN:'ドリ',SITRUS:'オボン',ORAN:'オレン',WIKI:'ウイ',CHESTO:'カゴ',RAWST:'チーゴ',BELUE:'ベリブ',YACHE:'ヤチェ'}};
const ISLANDS={{custom:{{name:'自由選択',berries:[]}},greengrass:{{name:'ワカクサ本島（ランダム）',berries:[]}},cyan:{{name:'シアンの砂浜',berries:['ORAN','PAMTRE','PECHA']}},taupe:{{name:'トープ洞窟',berries:['FIGY','LEPPA','SITRUS']}},snowdrop:{{name:'ウノハナ雪原',berries:['PERSIM','RAWST','WIKI']}},lapis:{{name:'ラピスラズリ湖畔',berries:['CHERI','DURIN','MAGO']}},powerplant:{{name:'ゴールド旧発電所',berries:['BELUE','BLUK','GREPA']}},amber:{{name:'アンバー渓谷',berries:['CHESTO','LUM','YACHE']}}}};
const options=o=>Object.entries(o).map(([v,n])=>`<option value="${{v}}">${{esc(n.name||n)}}</option>`).join('');
function teamControls(){{return `<article class="card"><div class="control-title"><span class="icon">🏝️</span><div><h2>フィールド設定</h2><div class="meta">島を選ぶときのみが自動で入ります</div></div></div><label class="field"><span>島・フィールド</span><select id="island">${{options(ISLANDS)}}</select></label><div class="berry-grid">${{[0,1,2].map(i=>`<label class="berry-field field"><span>きのみ ${{i+1}}</span><select class="berry">${{options(BERRIES)}}</select></label>`).join('')}}</div><div class="mode-row"><label class="field"><span>評価する育成段階</span><select id="team-mode"><option value="current">現在のレベル</option>${{[50,60,70,80].map(x=>`<option value="${{x}}">Lv${{x}}まで育成</option>`).join('')}}</select></label><p class="hint">きのみを直接変えると自由選択になります</p></div></article><section id="team-result"></section>`}}
function updateTeam(){{const favored=[...document.querySelectorAll('.berry')].map(x=>x.value),mode=document.querySelector('#team-mode').value;const ranked=DATA.map(x=>{{const p=x.production_scores?.[mode];if(!p)return null;const favorite=favored.includes(x.berry),score=Number(p.total)+(favorite?Number(p.berry):0);return {{...x,favorite,teamScore:Math.round(score*100)/100}}}}).filter(Boolean).sort((a,b)=>b.teamScore-a.teamScore).slice(0,5),total=Math.round(ranked.reduce((s,x)=>s+x.teamScore,0)*100)/100,max=Math.max(...ranked.map(x=>x.teamScore),1);document.querySelector('#team-result').innerHTML=`<div class="team-head"><div><div class="eyebrow">Recommended team</div><h2>${{mode==='current'?'いまの最強5匹':`Lv${{mode}} 育成後`}}</h2></div><div class="power"><span>TEAM POWER</span><strong>${{total}}</strong></div></div>${{ranked.length?`<div class="team-list">${{ranked.map((x,i)=>`<article class="member"><div class="rank">${{i+1}}</div><div><div class="member-name">${{esc(x.display_name||x.species)}}</div><div class="tags"><span class="tag">${{esc(x.pokemon_type||'タイプ未登録')}}</span><span class="tag ${{x.favorite?'favorite':''}}">${{x.favorite?'★ ':''}}${{BERRIES[x.berry]||x.berry||'きのみ未登録'}}</span></div><div class="scoreline"><i style="width:${{Math.round(x.teamScore/max*100)}}%"></i></div></div><div class="power"><span>POWER</span><strong>${{x.teamScore}}</strong></div></article>`).join('')}}</div>`:'<div class="card empty">生産スコアを取り込むと候補を表示します。</div>'}}`}}
function draw(tab){{document.querySelectorAll('[data-tab]').forEach(b=>{{const active=b.dataset.tab===tab;b.classList.toggle('active',active);b.setAttribute('aria-current',active?'page':'false')}});if(tab==='teams'){{document.querySelector('#list').innerHTML=teamControls();const bs=[...document.querySelectorAll('.berry')];bs.forEach((x,i)=>x.value=Object.keys(BERRIES)[i]);document.querySelector('#island').onchange=e=>{{const preset=ISLANDS[e.target.value].berries;if(preset.length)bs.forEach((x,i)=>x.value=preset[i]);updateTeam()}};bs.forEach(x=>x.onchange=()=>{{document.querySelector('#island').value='custom';updateTeam()}});document.querySelector('#team-mode').onchange=updateTeam;updateTeam();return}}const xs=DATA.filter(x=>(x.verdict||'protected')===tab).sort((a,b)=>(b.absolute_score||0)-(a.absolute_score||0));document.querySelector('#list').innerHTML=xs.length?xs.map(x=>{{const e=x.evaluations||{{}};const best=l=>Math.max(...Object.values(e[l]||{{0:0}}));return `<article class="card ${{tab}}"><div class="meta">BOX ${{x.box_index??'-'}} · Lv${{x.level??'-'}}</div><h2>${{esc(x.display_name||x.species)}} <small>${{x.absolute_score??0}} / 100</small></h2><p>${{esc(x.reason)}}</p><div class="scores">${{['50','60','70','80'].map(l=>`<div class="score">Lv${{l}}<br><strong>${{best(l)}}</strong></div>`).join('')}}</div><p class="meta">きのみ ${{x.absolute_by_role?.berry??0}}　食材 ${{x.absolute_by_role?.ingredient??0}}　スキル ${{x.absolute_by_role?.skill??0}}</p></article>`}}).join(''):'<div class="card empty">該当する個体はありません。</div>'}}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>draw(b.dataset.tab));draw('teams');</script></body></html>'''
    (out / "index.html").write_text(page, encoding="utf-8")
    (out / ".nojekyll").write_text("", encoding="utf-8")
